spring:
  application:
    name: big-event
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bigevent
    username: root
    password: 1234
mybatis:
  configuration:
    map-underscore-to-camel-case: true # ?????????????????
