spring:
  application:
    name: big-event
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  data:
    redis:
      host: ${spring.data.redis.host}
      port: 6379


mybatis:
  configuration:
    map-underscore-to-camel-case: true # 数据库下划线命名法自动对应java驼峰命名法


oss:
  endpoint: ${oss.endpoint}
  access-key-id: ${oss.access-key-id}
  access-key-secret: ${oss.access-key-secret}
  bucket-name: ${oss.bucket-name} # 阿里云存对象的相关配置